server:
  port: 8003

spring:
  application:
    name: service-video
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1024MB
      max-request-size: 1024MB

aliyun:
  video:
    bucketname: chins-edu-bucket
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAI5tDfrk6Uy3X9ZmGewjSG
    keysecret: 8k3pxxLNNvWN4Y0S0B3ZepkUvzeUtX
